# -*- coding: utf-8 -*-
"""mod1_ses5_distribuciones_muestrales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcUAH8l75YfZr-YI3FbYlDPFR3jcydwe

**Distribuciones muestrales**

Objetivo: En esta práctica, aprederemos a diferenciar entre una población y una muestra. También aprenderemos el Teorema del límite central.

Definición. Una **muestra aleatoria simple** es una colección finita de variables aleatorias $X_1, X_2, \ldots, X_n$ independientes e idénticamente distribuidas, provenientes de una población infinita.

Para ejemplificar el concepto de muestra, descargaremos los precios de los activos de apple (por día) del año 2025. Para esto, usaremos el paquete "yfinance" de Python.

Una vez que descarguemos los precios de los activos (clasificados como de apertura, máximo, mínimo y de cierre), calcularemos su rendimiento diario, que se interpreta como el porcentaje de crecimiento del precio de una acción de la empresa con respecto al día anterior.
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

apple = yf.download("AAPL", start="2025-01-01", end="2025-12-31")

"""Los precios de los activos de apple descargados, desde el 1 de enero de 2025 hasta el 31 de diciembre de 2025, son una muestra de la población de precios históricos de los activos de apple. Sin embargo, en este ejercicio, consideraremos estos datos descargados como "nuestra" población."""

print(apple.head())

"""Grafiquemos los precios de cierre de los activos de apple descargados:"""

plt.figure(figsize=(10,5))
plt.plot(apple["Close"], label="Apple")
plt.legend()
plt.title("Precios históricos")
plt.show()

"""Calculemos el rendimiento diario, **R_t**, de Apple, usando la siguiente fórmula:

$$R_t = \frac{P_t-P_{t-1}}{P_{t-1}}$$

Con el método **pct_change()** de Python calcularemos el rendimiento diario:
"""

apple_returns = apple["Close"].pct_change()

"""Con los rendimientos diarios (de cierre) de apple, estamos construyendo "otra" población de datos."""

apple_returns.head()

"""Como se observa en la salida de apple_returns, hay datos no definidos (Nan). Para depurar los datos (borrar los datos no definidos), se usa el método **dropna**. Renombraremos al archivo apple_returns como "data":"""

data = apple_returns.dropna()

data.head()

"""Número actual de datos "limpios":"""

len(data)

"""Vamos a construir una función que nos permita extraer aleatoriamente una muestra del conjunto "data":"""

def generate_random_sample(data, sample_size):
  return np.random.choice(data, size=sample_size, replace=False)

"""En nuestro ejemplo, el conjunto "data" tiene un formato de tabla. Para extraer sólo los valores, usaremos el método **squeeze().values**.
Nota: Intentar ejecutar la línea de código "generate_random_sample(data, sample_size)" sin la instrucción squeeze().values produce un error, y por lo tanto, no se extrae ninguna muestra.
"""

sample_size = 20
random_returns_sample = generate_random_sample(data.squeeze().values, sample_size)

"""Nota. cada vez que corremos la línea de código "generate_random_sample(data.squeeze().values, sample_size)", estamos extrayendo otra muestra aleatoria de tamaño "sample_size" (en este caso igual a 20) del conjunto "data". En nuestro caso, usaremos 100 veces esta función para extraer 100 muestras aleatorias "diferentes" de tamaño 20.

Construiremos una lista (llamada "lista") de tamaño 100 sobre la que, al editar sus entradas (o valores), podamos almacenar el promedio de cada muestra de tamaño 20 del conjunto "data":
"""

lista = list(range(100))

"""Con la siguiente ventana de código, estamos guardando en la "lista" los promedios de cada muestra de tamaño 20."""

sample_size = 20
for i in range(100):
   lista[i] = np.mean(generate_random_sample(data.squeeze().values, sample_size))

"""Leamos unos valores de la lista:"""

lista[0]

lista[4]

lista[99]

"""Antes de continuar, vale la pena aclarar que acabamos de construir otra población de datos, "lista". Dicha población tiene 100 elementos (cada elemento es el promedio de 20 rendimientos aleatorios extraídos de "data"). El conjunto "lista" tiene asociado una distribución de frecuencias, $\bar{X}$, desconocida. Pero el Teorema del límite central predice la distribución de otra variable aleatoria, $Z = \frac{\bar{X}-\mu}{\sigma/\sqrt{n}}$. Dentro del contexto estadístico, decimos que $Z$ es la estandarización de $\bar{X}$ (con más simpleza, podemos decir que hicimos un *cambio de variable* **conveniente**).

**Teorema del límite central (TLC)**. Sea $X_1, X_2, \ldots, X_n$ una muestra aleatoria simple proveniente de una población infinita de media $\mu$ y varianza $\sigma^2$, entonces la distribución límite de $Z = lim_{n→∞}\frac{\bar{X}-\mu}{\sigma/\sqrt{n}}$ tiene la distribución normal estándar.

Para estandarizar $\bar{X}$, haremos el truco de antes de construir otro conjunto, llamado "lista2" (de elementos iniciales 0,1,2,...,99). Después modificaremos sus elementos, redefiniéndolos en la forma "lista2[0]=", "lista2[1]=",...,"list2[99]"=.
"""

lista2 = list(range(100))

for i in range(100):
  lista2[i] = (lista[i]-np.mean(data.squeeze().values))/(np.std(data.squeeze().values,ddof=0)/np.sqrt(20))

"""Observe que cada valor "lista2[i]" lo hemos redefinido a partir de la fórmula $\frac{lista[i]-\mu}{\sigma/\sqrt{n}}$, donde $\mu=$np.mean(data.squeeze().values) y $\sigma$=np.std(data.squeeze().values,ddof=0).

Veamos algunos elementos de la "lista2":
"""

lista2[0]

lista2[44]

lista2[17]

"""Aclaro que la distribución de frecuencias para "lista2" no cumple las hipótesis del teorema del límite central. Sólo la cumple en apariencia:

El teorema del límite central depende de una población infinita, pero en nuestro caso la "lista" sólo tiene 100 elementos. La variable aleatoria $Z$ del teorema, contempla una distribución límite, es decir, cocientes asociados a muestras de tamaño infinito. En nuestro caso, los cocientes están asociados a muestras de tamaño 20. Pese a estas discrepancias, en este ejercicio estamos aproximando a la distribución de "lista2" a  la distribución normal estándar.

A continuación, graficaremos la distribución de frecuencias para "lista2", y notaremos que parece ajustarse a una distribución normal estándar (campana centrada en el origen).
"""

import matplotlib.pyplot as plt

plt.hist(
    lista2,
    bins=30,
    density=True
)

plt.show()

"""Aproximando la distribución de "lista2" a la distribución normal estándar, **¡¡¡podemos plantearnos preguntas con relación a la "lista"!!!**

Por ejemplo, qué tan probable es que, al elegir un rendimiento diario para la empresa apple, tomado del conjunto "lista", su valor esté entre 0.003 y 0.007.

Solución. Nos están solicitando "medir" la probabilidad de observar el evento $0.003 \leq \bar{X} \leq 0.007$. Este evento es equivalente a $\frac{0.003-\mu}{\sigma/\sqrt{20}} \leq Z\approx \frac{\bar{X}-\mu}{\sigma/\sqrt{20}} \leq \frac{0.007-\mu}{\sigma/\sqrt{20}}$, cuya probabilidad podemos calcularla con la función de densidad normal estándar.

Para continuar, visualicemos $\mu$ y $\sigma$:

"""

mu = np.mean(data.squeeze().values)
mu

sigma = np.std(data.squeeze().values,ddof=0)
sigma

from numpy.ma import sqrt
from scipy.stats import norm
# Distribución Normal

# media y desvación estándar de lista
mu # Media
sigma # Desviación estándar

# Calcular la probabilidad de Z (variable aproximadamente normal estándar por aplicacion de TLC)
# esté entre z1 y z2 (valores estandarizados de x1=0.003 y x2=0.007)
x1 = 0.003
x2 = 0.007
z1 = (x1-mu)/(sigma/sqrt(20))
z2 = (x2-mu)/(sigma/sqrt(20))
probabilidad = norm.cdf(z2, loc=0, scale=1) - norm.cdf(z1, loc=0, scale=1)
print(f"La probabilidad de que la variable X esté entre {x1} y {x2} es: {probabilidad}")

"""**Ejercicios sobre el Teorema del Límite Central (TLC)**

**Instrucciones:**
En todos los ejercicios, suponga que las observaciones son independientes y provienen de una población con media y varianza finitas. Utilice el Teorema del Límite Central para responder las preguntas planteadas.

**Nota.** En cada ejercicio, sólo hay que definir las variables $x1$, $x2$, $\mu$ y $\sigma$. Después hay que usa la instrucción

"probabilidad = norm.cdf(z2, loc=0, scale=1) - norm.cdf(z1, loc=0, scale=1)"

**Ejercicio 1. Producción industrial de tornillos**

Una fábrica produce tornillos cuyo peso presenta una media de 8 gramos y una desviación estándar de 1.5 gramos.

Se selecciona una muestra aleatoria de 100 tornillos.

¿Cuál es la probabilidad de que el peso promedio de la muestra sea menor que 7.8 gramos?
¿Cuál es la probabilidad de que el peso promedio de la muestra esté entre 7.9 y 8.2 gramos?
"""

import numpy as np
from scipy.stats import norm

# Ejercicio 1. Producción industrial de tornillos
# Datos proporcionados
mu_tornillos = 8  # Media del peso de los tornillos en gramos
sigma_tornillos = 1.5  # Desviación estándar del peso de los tornillos en gramos
n_tornillos = 100  # Tamaño de la muestra

print("Ejercicio 1. Producción industrial de tornillos")

# Pregunta 1: ¿Cuál es la probabilidad de que el peso promedio de la muestra sea menor que 7.8 gramos?
x1_q1 = 7.8
z1_q1 = (x1_q1 - mu_tornillos) / (sigma_tornillos / np.sqrt(n_tornillos))
probabilidad_q1 = norm.cdf(z1_q1, loc=0, scale=1)
print(f"La probabilidad de que el peso promedio de la muestra sea menor que {x1_q1} gramos es: {probabilidad_q1:.4f}")

# Pregunta 2: ¿Cuál es la probabilidad de que el peso promedio de la muestra esté entre 7.9 y 8.2 gramos?
x1_q2 = 7.9
x2_q2 = 8.2

z1_q2 = (x1_q2 - mu_tornillos) / (sigma_tornillos / np.sqrt(n_tornillos))
z2_q2 = (x2_q2 - mu_tornillos) / (sigma_tornillos / np.sqrt(n_tornillos))
probabilidad_q2 = norm.cdf(z2_q2, loc=0, scale=1) - norm.cdf(z1_q2, loc=0, scale=1)
print(f"La probabilidad de que el peso promedio de la muestra esté entre {x1_q2} y {x2_q2} gramos es: {probabilidad_q2:.4f}")

"""**Ejercicio 2. Gasto diario de consumidores**

Un supermercado ha determinado que el gasto diario por cliente tiene una media de $420 y una desviación estándar de $180.

Durante un día se registra una muestra aleatoria de 64 clientes.

¿Cuál es la probabilidad de que el gasto promedio de la muestra exceda los 450?
¿Cuál es la probabilidad de que el gasto promedio de la muestra sea inferior a $400?
"""

import numpy as np
from scipy.stats import norm

# Ejercicio 2. Gasto diario de consumidores
# Datos proporcionados
mu_gasto = 420  # Media del gasto diario por cliente
sigma_gasto = 180  # Desviación estándar del gasto diario por cliente
n_gasto = 64  # Tamaño de la muestra

print("\nEjercicio 2. Gasto diario de consumidores")

# Pregunta 1: ¿Cuál es la probabilidad de que el gasto promedio de la muestra exceda los 450?
x1_q1 = 450
z1_q1 = (x1_q1 - mu_gasto) / (sigma_gasto / np.sqrt(n_gasto))
probabilidad_q1 = 1 - norm.cdf(z1_q1, loc=0, scale=1)
print(f"La probabilidad de que el gasto promedio de la muestra exceda los {x1_q1} es: {probabilidad_q1:.4f}")

# Pregunta 2: ¿Cuál es la probabilidad de que el gasto promedio de la muestra sea inferior a $400?
x1_q2 = 400
z1_q2 = (x1_q2 - mu_gasto) / (sigma_gasto / np.sqrt(n_gasto))
probabilidad_q2 = norm.cdf(z1_q2, loc=0, scale=1)
print(f"La probabilidad de que el gasto promedio de la muestra sea inferior a {x1_q2} es: {probabilidad_q2:.4f}")

"""**Ejercicio 3. Tiempo de atención en un centro de soporte técnico**

Una empresa de telecomunicaciones sabe que el tiempo de atención de una llamada tiene una media de 12 minutos y una desviación estándar de 5 minutos.

En un determinado turno se observan 81 llamadas seleccionadas aleatoriamente.

¿Cuál es la probabilidad de que el tiempo promedio de atención sea menor que 11 minutos?
¿Cuál es la probabilidad de que el tiempo promedio se encuentre entre 11.5 y 13 minutos?
"""

import numpy as np
from scipy.stats import norm

# Ejercicio 3. Tiempo de atención en un centro de soporte técnico
# Datos proporcionados
mu_tiempo = 12  # Media del tiempo de atención en minutos
sigma_tiempo = 5  # Desviación estándar del tiempo de atención en minutos
n_tiempo = 81  # Tamaño de la muestra

print("\nEjercicio 3. Tiempo de atención en un centro de soporte técnico")

# Pregunta 1: ¿Cuál es la probabilidad de que el tiempo promedio de atención sea menor que 11 minutos?
x1_q1 = 11
z1_q1 = (x1_q1 - mu_tiempo) / (sigma_tiempo / np.sqrt(n_tiempo))
probabilidad_q1 = norm.cdf(z1_q1, loc=0, scale=1)
print(f"La probabilidad de que el tiempo promedio de atención sea menor que {x1_q1} minutos es: {probabilidad_q1:.4f}")

# Pregunta 2: ¿Cuál es la probabilidad de que el tiempo promedio se encuentre entre 11.5 y 13 minutos?
x1_q2 = 11.5
x2_q2 = 13

z1_q2 = (x1_q2 - mu_tiempo) / (sigma_tiempo / np.sqrt(n_tiempo))
z2_q2 = (x2_q2 - mu_tiempo) / (sigma_tiempo / np.sqrt(n_tiempo))
probabilidad_q2 = norm.cdf(z2_q2, loc=0, scale=1) - norm.cdf(z1_q2, loc=0, scale=1)
print(f"La probabilidad de que el tiempo promedio se encuentre entre {x1_q2} y {x2_q2} minutos es: {probabilidad_q2:.4f}")

"""**Ejercicio 4. Rendimiento de una cartera de microcréditos**

Una institución financiera ha estimado que la utilidad anual por crédito otorgado tiene una media de 1,200 pesos y una desviación estándar de 600 pesos.

Se selecciona aleatoriamente una cartera de 225 créditos.

¿Cuál es la probabilidad de que la utilidad promedio de los créditos de la cartera sea superior a 1,260 pesos?
¿Cuál es la probabilidad de que la utilidad promedio se encuentre entre 1,150 y 1,300 pesos?
"""

import numpy as np
from scipy.stats import norm

# Ejercicio 4. Rendimiento de una cartera de microcréditos
# Datos proporcionados
mu_creditos = 1200  # Media de la utilidad anual por crédito en pesos
sigma_creditos = 600  # Desviación estándar de la utilidad anual por crédito en pesos
n_creditos = 225  # Tamaño de la muestra

print("\nEjercicio 4. Rendimiento de una cartera de microcréditos")

# Pregunta 1: ¿Cuál es la probabilidad de que la utilidad promedio de los créditos de la cartera sea superior a 1,260 pesos?
x1_q1 = 1260
z1_q1 = (x1_q1 - mu_creditos) / (sigma_creditos / np.sqrt(n_creditos))
probabilidad_q1 = 1 - norm.cdf(z1_q1, loc=0, scale=1)
print(f"La probabilidad de que la utilidad promedio de los créditos de la cartera sea superior a {x1_q1} pesos es: {probabilidad_q1:.4f}")

# Pregunta 2: ¿Cuál es la probabilidad de que la utilidad promedio se encuentre entre 1,150 y 1,300 pesos?
x1_q2 = 1150
x2_q2 = 1300

z1_q2 = (x1_q2 - mu_creditos) / (sigma_creditos / np.sqrt(n_creditos))
z2_q2 = (x2_q2 - mu_creditos) / (sigma_creditos / np.sqrt(n_creditos))
probabilidad_q2 = norm.cdf(z2_q2, loc=0, scale=1) - norm.cdf(z1_q2, loc=0, scale=1)
print(f"La probabilidad de que la utilidad promedio se encuentre entre {x1_q2} y {x2_q2} pesos es: {probabilidad_q2:.4f}")